/*
  # Création d'un nouvel article sur les taxes douanières de Trump (version corrigée)

  1. Contenu
    - Ajout d'un nouvel article sur l'analyse des taxes douanières de Trump
    - Inclut titre, slug, résumé, contenu complet et image
    - Vérifie d'abord si l'article existe déjà pour éviter les doublons
*/

-- Vérifier si l'article existe déjà avec ce slug
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM articles WHERE slug = 'analyse-taxes-douanieres-trump-impact-economie-mondiale') THEN
    -- Insérer l'article seulement s'il n'existe pas déjà
    INSERT INTO articles (
      title,
      slug,
      summary,
      content,
      image_url,
      created_at,
      updated_at
    )
    VALUES (
      'Analyse des nouvelles taxes douanières de Donald Trump et de leur impact sur l''économie mondiale',
      'analyse-taxes-douanieres-trump-impact-economie-mondiale',
      'Une analyse approfondie des récentes mesures protectionnistes de Donald Trump, leurs conséquences sur les marchés financiers, les cryptomonnaies et l''économie mondiale.',
      '## Contexte politique et économique des annonces 
Le **président Donald Trump** a récemment provoqué un séisme commercial en annonçant une hausse massive des droits de douane sur les importations américaines. Le 2 avril (surnommé par son administration le *« Liberation Day »*), il a dévoilé des tarifs « réciproques » d''au **minimum 10 %** sur tous les produits importés aux États-Unis, avec des taux encore supérieurs pour certains partenaires clés. Concrètement, les marchandises en provenance de l''**Union européenne** seront taxées à **20 %**, celles de **Chine** à **34 %**, et le **Japon** à **24 %** dès l''entrée en vigueur des mesures le 5 avril. Seuls de rares pays alliés échappent à ces surtaxes générales : le **Canada** et le **Mexique** conservent un accès exempt de droits de douane dans le cadre de l''accord USMCA, tout comme certains produits stratégiques (énergie, minerais indispensables non produits aux États-Unis) ou déjà sous le coup d''autres taxes spécifiques (acier, aluminium, automobile).

Trump justifie politiquement ce tournant protectionniste comme une défense des intérêts américains et l''aboutissement de sa doctrine **« America First »**. Il affirme vouloir mettre fin à ce qu''il considère comme des pratiques commerciales « inéquitables » qui pénaliseraient les États-Unis. Lors d''une mise en scène télévisée, tableau de chiffres à l''appui, il a présenté l''Amérique en « victime de sa générosité », exploitée par les excédents de la **Chine** et de l''**Europe**. Ces tarifs douaniers seraient selon lui simplement destinés à obtenir la "réciprocité" commerciale et à corriger des déficits chroniques. Son administration a d''ailleurs calculé ces taux de manière mécanique : en divisant par deux le ratio du déficit commercial américain sur les importations depuis chaque pays. Une telle méthode aboutit à des résultats extrêmes – par exemple, de petits pays avec lesquels les États-Unis ont un léger déficit se retrouvent frappés d''un tarif exorbitant de **50 %** (c''est le cas du Lesotho, l''un des pays les plus pauvres du monde). **Presque aucun pays n''échappe** donc à la stratégie de Donald Trump, et chaque dirigeant étranger est confronté à un dilemme : comment réagir face à cette offensive protectionniste sans précédent ?

Cette rupture avec des décennies de libéralisation commerciale marque un **virage historique**. Le tarif moyen effectif des importations américaines pourrait bondir à **26,2 %** (contre seulement 2,3 % en 2024), atteignant son plus haut niveau depuis plus d''un siècle. Il s''agit du changement le plus brutal depuis la loi protectionniste Smoot-Hawley de 1930, tristement célèbre pour avoir aggravé la Grande Dépression. En tournant le dos aux règles multilatérales de l''OMC, ces mesures risquent de déclencher une spirale de représailles et d''ébranler l''édifice du libre-échange mondial. Trump, fort de son mandat politique, assume toutefois ce bras de fer commercial, espérant en tirer des bénéfices intérieurs – relocalisations d''industries, réduction du déficit commercial, recettes douanières supplémentaires – et un levier de négociation vis-à-vis de ses partenaires. Reste à évaluer les conséquences concrètes d''un tel choc protectionniste sur les différentes économies du globe.

## Impact aux États-Unis : entre inflation et risque de récession 
Ironiquement, la première économie touchée par ces taxes pourrait bien être celle des **États-Unis** eux-mêmes. À court terme, les importateurs américains devront s''acquitter de ces droits de douane majorés, un surcoût qui sera en grande partie répercuté sur les consommateurs domestiques. En effet, les expériences passées montrent que ce sont les acheteurs américains qui payent le prix des tarifs : les exportateurs étrangers n''ont globalement pas baissé leurs prix pour compenser, contrairement à ce que prétend Donald Trump. Lorsque Trump assure que « ce sont les autres qui paieront », la réalité est tout autre : ces taxes se traduiront par des hausses de prix pour les ménages américains. 

Cette inflation importée pourrait peser lourdement sur un pouvoir d''achat déjà fragile. L''économie américaine montrait justement des **signes de faiblesse début 2025** – les dépenses des ménages n''ont progressé que de +0,1 % en février, après avoir même reculé en janvier. En renchérissant de nombreux biens de consommation (électronique, vêtements, machines-outils, etc.), les tarifs risquent d''éroder encore la consommation et de freiner les investissements des entreprises. Des économistes estiment que ces hausses de droits de douane, si elles perdurent, pourraient ajouter **jusqu''à 2 points** à l''inflation américaine. Avec une inflation annuelle déjà projetée autour de 2,8 %, une telle poussée inflationniste compliquerait sérieusement la tâche de la Réserve fédérale. La banque centrale se retrouverait face à un **dilemme de politique monétaire** : comment assouplir les taux pour soutenir une économie en ralentissement, sans attiser une inflation dopée par les tarifs douaniers ?

Les milieux d''affaires américains redoutent également des **mesures de représailles** étrangères qui pénaliseraient les exportateurs américains. Plusieurs géants industriels et agricoles américains dépendent fortement des débouchés étrangers – qu''il s''agisse de Boeing pour les avions, de l''agroalimentaire (soja, produits carnés) ou des machines-outils. Or, en retour des taxes Trump, leurs produits risquent d''être lourdement taxés en Chine, en Europe ou ailleurs, les rendant moins compétitifs. Déjà, les marchés financiers anticipent une **probabilité de récession élevée** aux États-Unis si la guerre commerciale s''intensifie, tant le choc sur la demande et la confiance pourrait être brutal. Le patron de la banque JPMorgan a publiquement exprimé sa crainte que ces droits de douane "augmentent probablement l''inflation" tout en "ralentissant la croissance" – un cocktail stagflationniste redouté par les investisseurs.

Sur le plan politique intérieur, Donald Trump mise pourtant sur un gain populaire : apparaître comme le défenseur des travailleurs face aux « profiteurs » étrangers. Il table sur un rapatriement de certaines usines et sur les recettes douanières pour renforcer l''économie américaine. Cependant, ces recettes supplémentaires restent modestes au regard du budget fédéral (en 2024, les droits de douane n''ont rapporté que 88 milliards $, soit à peine 1,5 % des recettes totales). Et les objectifs affichés – réduction du déficit commercial, réindustrialisation – sont loin d''être garantis. Les déséquilibres commerciaux relèvent avant tout de facteurs macroéconomiques (épargne, investissement, taux de change) bien plus que des barrières tarifaires. En outre, les droits de douane n''aborderont pas certaines **faiblesses structurelles** entravant le "Made in America", comme le coût de la main-d''œuvre ou les pénuries de compétences dans l''industrie. En somme, à moyen terme l''économie américaine pourrait sortir fragilisée de cette confrontation commerciale, avec des consommateurs payant plus cher et des entreprises moins enclines à investir dans un climat incertain. 

## Conséquences en Chine : riposte ferme et incertitudes 
La **Chine**, cible privilégiée de Donald Trump, n''a pas tardé à réagir à cette offensive. Pékin a immédiatement dénoncé des mesures visant à assouvir "l''hégémonie [américaine] au nom de la réciprocité". Surtout, fait inédit, les autorités chinoises ont lancé une **riposte d''envergure symétrique**. Dès le 3 avril, la Chine a annoncé **34 % de droits de douane** sur l''ensemble des produits en provenance des États-Unis, soit un niveau équivalent aux taxes imposées par Washington aux marchandises chinoises. En parallèle, Pékin utilise ses armes stratégiques : des **restrictions aux exportations de minerais critiques** ont été décidées. Cela vise notamment les terres rares et autres métaux dont l''industrie américaine (en particulier le secteur des technologies et des énergies renouvelables) est fortement dépendante. La réaction chinoise, qualifiée d''"extrêmement dure" par les analystes, marque une escalade sans précédent : "C''est la première fois que la Chine réagit de la sorte à des droits de douane. En 2018, cela n''avait pas du tout été le cas : les représailles chinoises étaient restées ciblées sur quelques secteurs. Là, on a des droits de douane généralisés à 34 %, couplés à des restrictions d''exportation de minerais essentiels". En d''autres termes, Pékin montre qu''elle est prête à soutenir un **bras de fer prolongé**. 

Les conséquences se font déjà sentir sur l''économie chinoise et régionale. La perspective d''une fermeture (même partielle) du marché américain et d''un renchérissement des échanges a semé la panique sur les bourses asiatiques. À Hong Kong, l''indice **Hang Seng** a chuté de plus de **12 %** dans la foulée des annonces et des contre-mesures chinoises, et la bourse de Shanghai a également lourdement décroché. Les investisseurs redoutent un coup de frein au commerce sino-américain, qui pourrait priver la Chine d''une part importante de ses revenus d''exportation et peser sur sa croissance déjà ralentissante. Pour rassurer, Pékin a déclaré vouloir demeurer *"une terre d''accueil sûre pour les investissements étrangers"*, promettant de protéger les entreprises américaines implantées en Chine malgré le conflit. Cette communication vise à éviter une fuite des capitaux ou des délocalisations en chaîne d''usines vers d''autres pays d''Asie. Néanmoins, l''incertitude grandit parmi les industriels : dans quelle mesure la Chine pourra-t-elle absorber le choc d''une guerre commerciale prolongée ?

À moyen terme, la Chine pourrait accélérer sa stratégie de **réorientation de ses marchés**. Si l''accès au marché américain se réduit, Pékin cherchera à intensifier ses échanges avec d''autres partenaires. On pourrait voir la Chine renforcer ses liens commerciaux en Asie (via l''accord RCEP par exemple), en Europe ou en Afrique pour compenser la baisse des exportations vers les USA. Ironie de l''histoire, en se voyant ainsi pousser hors du marché américain, la Chine risque d''inonder d''autres régions avec ses produits excédentaires, au risque de créer un *« choc d''offre »* sur ces marchés alternatifs. Les experts avertissent que si la production chinoise se réoriente massivement vers l''Europe, par exemple, cela pourrait **déstabiliser les industries locales européennes** en inondant le marché de produits bon marché. En parallèle, la Chine dispose d''atouts pour **tenir sur la durée** : son vaste marché intérieur peut soutenir la demande pour certaines industries, et l''État chinois peut stimuler l''économie via des plans de relance ou des assouplissements monétaires si nécessaire. Cependant, une guerre commerciale prolongée sino-américaine aurait un coût élevé pour Pékin, menaçant des millions d''emplois tournés vers l''export et compliquant la montée en gamme technologique du pays si l''accès aux composants étrangers se resserre. Le gouvernement chinois, tout en affichant sa fermeté, pourrait donc chercher en coulisses des voies de dialogue pour éviter une détérioration durable de son environnement économique.

## Conséquences en Europe : économie sous tension et préparation de représailles 
L''**Europe**, traditionnellement alliée des États-Unis mais visée par ces nouvelles taxes, encaisse elle aussi un choc considérable. L''annonce de **droits de douane de 20 %** sur l''ensemble des produits européens exportés vers le marché américain a immédiatement fait trembler les secteurs clés du Vieux Continent. Pour l''Union européenne, le marché américain reste l''un des débouchés les plus importants, et une hausse brutale de tarifs est synonyme de pertes de parts de marché face à des concurrents non taxés ou domestiques. *"Aujourd''hui, certains produits européens ne sont pas du tout taxés à l''entrée des États-Unis. Pour ceux-là, passer soudainement à 20 %, c''est une rupture nette"*, souligne une économiste spécialiste du commerce international. En effet, de nombreuses industries européennes vont voir leurs biens devenir nettement plus chers outre-Atlantique, ce qui pourrait les rendre moins compétitifs et faire chuter les volumes exportés.

Les pays européens les plus exposés sont ceux qui exportent massivement vers les États-Unis. L''**Allemagne** et l''**Italie**, grands pays manufacturiers tournés vers l''export, sont particulièrement vulnérables. Dès l''annonce des tarifs Trump, la Bourse de Francfort a connu un véritable **krach** : l''indice **DAX** a plongé de 10 % en une seule séance, effaçant ses gains de l''année. À Paris, le CAC 40 a chuté de près de 7 % à l''ouverture le 7 avril, les investisseurs anticipant une possible récession provoquée par cette *« guerre douanière »*. Ces réactions boursières illustrent la crainte d''un coup d''arrêt de la croissance européenne, déjà affaiblie par des mois d''incertitudes. L''**industrie automobile allemande** – très dépendante du marché américain pour ses berlines haut de gamme – redoute en particulier l''imposition d''un tarif spécifique de 25 % sur les voitures importées, annoncé dans le sillage des mesures de Trump. Une telle taxe, applicable immédiatement aux BMW, Mercedes, Audi et autres véhicules assemblés hors des USA, pourrait lourdement pénaliser ce secteur emblématique. En France, ce sont les filières **aéronautique**, **vins et spiritueux** et **luxe** (cosmétiques, mode) qui figurent parmi les plus touchées, compte tenu de leur volume d''exportations vers les États-Unis. Par exemple, les producteurs de vin et de cognac, pour lesquels l''Amérique représente 25 à 40 % des débouchés, estiment risquer un manque à gagner de **800 millions d''euros** d''exportations.

Face à cette attaque commerciale, l''Union européenne organise la **riposte**. Dès les premiers jours, les dirigeants européens ont affiché une unité de ton rare. *"Ne soyez pas faibles !"* a exhorté Donald Trump dans une provocation, mais l''**UE** a répondu qu''elle utiliserait "**tous les outils** de son arsenal de défense commerciale" pour défendre ses intérêts. Concrètement, Bruxelles prépare des **contre-mesures ciblées**. Une première vague de droits de douane européens sur des produits emblématiques américains est prévue dès le 15 avril, puis une seconde vague le 15 mai. Les détails ne sont pas entièrement publics, mais on sait que l''Europe envisage de frapper des secteurs sensibles pour les États-Unis. Une piste discutée par les ministres européens du Commerce est de **cibler les géants du numérique américains** (les GAFAM) et leurs services, en augmentant la taxation sur ces activités. L''idée serait de toucher des entreprises comme Google, Apple, Amazon ou Facebook, très profitables en Europe, afin de faire pression sur Washington. Toutefois, certains États membres se montrent prudents pour ne pas surenchérir dangereusement – l''Irlande, par exemple, juge qu''attaquer frontalement la tech américaine serait *"une escalade"* qui pourrait se retourner contre l''Europe.

D''autres produits américains pourraient être mis dans la ligne de mire des Européens, calqués sur les précédentes représailles de 2018 : les motos Harley-Davidson, le bourbon du Kentucky, le jean Levi''s ou le beurre de cacahuète avaient été symboliquement taxés lors du premier bras de fer, et pourraient l''être à nouveau. De son côté, **Berlin** a qualifié l''effondrement des marchés financiers de "signal d''alarme", appelant à tout faire pour éviter une détérioration durable du climat économique. La **France**, par la voix de son ministre de l''Économie, a prévenu que la réponse européenne pourrait être *"extrêmement agressive"* si les États-Unis persistaient à ignorer les règles du jeu. L''Europe dispose aussi depuis peu d''un **"Instrument anti-coercition"**, nouvel outil adopté fin 2023, qui pourrait être utilisé pour la première fois contre les États-Unis. Cet instrument permettrait à l''UE de prendre des mesures de rétorsion rapides et coordonnées en cas de pression économique jugée abusive. En somme, la tension commerciale transatlantique monte rapidement et menace de s''élargir à d''autres domaines (tech, propriété intellectuelle, normes) si aucun apaisement n''est trouvé. 

## Répercussions sur les autres grandes économies 
Au-delà des trois grands pôles économiques, les **effets d''entraînement** de cette guerre commerciale se propagent à travers le monde. **Aucun continent n''est épargné**. En Asie, de nombreux pays émergents dépendants des exportations vers les États-Unis subissent de plein fouet la nouvelle donne. Des économies dynamiques comme le **Vietnam**, la **Thaïlande**, la **Malaisie**, **Taïwan** ou le **Cambodge** – intégrées aux chaînes d''approvisionnement mondiales et exportant massivement vers le marché américain – voient leurs produits désormais lourdement taxés à l''entrée des États-Unis. D''après les estimations, ces pays se retrouvent avec des tarifs douaniers allant de 32 % jusqu''à près de 49 % pour les plus touchés, selon l''ampleur de leur excédent commercial avec Washington. Par exemple, la **Suisse asiatique** qu''est **Taïwan**, menacée d''une taxe de 32 %, a choisi de ne **pas riposter** par des représailles équivalentes. Taipei préfère jouer l''apaisement : l''île a annoncé vouloir augmenter ses investissements industriels aux États-Unis et réduire certaines de ses propres barrières douanières, dans l''espoir de **négocier une exemption** ou un allègement auprès de l''administration Trump. De même, des pays d''Asie du Sud-Est comme le **Vietnam** ou la **Thaïlande** préparent activement le terrain diplomatique pour obtenir des traitements de faveur, conscients qu''ils ont beaucoup à perdre dans un conflit frontal.

Sur le continent européen hors UE, des pays comme la **Suisse** se retrouvent également dans une position délicate. Berne, qui exporte bien plus vers les États-Unis qu''elle n''importe, a hérité d''un tarif douanier de **31 %** sur ses produits (sauf les pharmaceutiques qui sont épargnés). C''est l''un des taux les plus élevés imposés, reflétant l''excédent suisse vis-à-vis des USA. La bourse de Zurich a fortement chuté à cette annonce. Pourtant, la **Confédération helvétique** a fait le choix surprenant de ne pas surenchérir : **aucune mesure de rétorsion** n''est prévue par la Suisse, qui veut éviter d''"augmenter la pression" dans l''escalade. Ne faisant pas partie de l''UE, la Suisse ne peut compter que sur elle-même et juge qu''une guerre tarifaire bilatérale ne ferait qu''aggraver la situation. *"Des mesures de représailles commerciales ne font aucun sens"*, a déclaré un économiste suisse, estimant que le pays doit plutôt miser sur sa capacité d''innovation et de résilience pour surmonter le choc.

Dans les économies **d''Asie développée**, le choc est aussi notable. La **Corée du Sud** et le **Japon**, tous deux alliés des États-Unis mais gros exportateurs (automobile, électronique, machines), figurent parmi les grands perdants de ces mesures. Séoul et Tokyo, confrontés à des tarifs d''environ 24 %, ont exprimé leur préoccupation et entamé des discussions discrètes avec Washington pour alléger la pression. Le Japon envisage par exemple des concessions ou ajustements tarifaires limités pour **alléger les taxes américaines** sur certains produits, cherchant à tout prix à maintenir la relation commerciale stable. La **République de Corée**, de son côté, pourrait accélérer la diversification de ses exportations vers l''Europe ou l''Asie du Sud-Est pour compenser d''éventuelles pertes sur le marché américain. 

En **Inde** également, on craint les retombées : l''Inde exporte moins vers les États-Unis que la Chine ou l''Europe, mais certains secteurs (textile, bijoux, technologies) y sont bien implantés et pourraient souffrir du renchérissement de leurs produits. New Delhi, qui a déjà eu des démêlés commerciaux avec Washington par le passé, doit choisir entre protéger ses producteurs via des négociations ou profiter des opportunités de substitution si la Chine et d''autres pays voient leurs exportations vers les US diminuer. 

Enfin, dans de nombreuses économies **d''Afrique** et d''**Amérique latine**, le contrecoup se fera sentir de façon indirecte. D''un côté, certains pays pauvres d''Afrique (comme le Lesotho, Madagascar) pâtiront de droits de douane très élevés sur leurs rares exportations vers l''Amérique, ce qui menace leurs industries naissantes. D''un autre côté, le ralentissement attendu du commerce mondial pourrait peser sur la demande de matières premières, *ce qui toucherait durement les pays exportateurs de commodités*. Par exemple, la baisse de la production industrielle mondiale a déjà entraîné un fléchissement des cours du **pétrole** : le baril de WTI américain est tombé en dessous de 60 $ (son plus bas niveau en 4 ans) en anticipant le coup de frein économique dû aux tarifs. Des pays comme le **Brésil** ou l''**Argentine**, exportateurs de soja, de minerais ou de viande vers la Chine et les États-Unis, risquent d''y perdre si la demande mondiale se contracte et si les prix des matières premières chutent. À l''inverse, quelques économies pourraient opportunément tirer leur épingle du jeu : par exemple le **Mexique** et le **Canada**, grâce à leur exemption via l''USMCA, pourraient gagner des parts de marché aux États-Unis au détriment d''autres pays désormais soumis à taxes (un avantage temporaire qui n''est cependant pas garanti dans un contexte de récession générale). Globalement, la fragmentation du commerce mondial accentue l''incertitude pour tous les acteurs économiques, grands ou petits, et redessine déjà les flux d''échanges internationaux. 

## Choc sur les marchés financiers et les cryptomonnaies 
Les annonces tarifaires de Trump ont provoqué une onde de choc instantanée sur les **marchés financiers mondiaux**. Les investisseurs, craignant un emballement de la guerre commerciale et ses effets récessifs, ont déclenché une vaste correction boursière. Aux États-Unis, dès le 2 avril au soir, Wall Street a piqué du nez : le **S&P 500** a perdu près de **4,8 %**, le **Nasdaq** plus de **5,4 %**, et le Dow Jones environ **4 %** en une seule séance. Cela représente une destruction de richesse boursière estimée à **2 900 milliards de dollars** en une journée à New York. Les secteurs les plus exposés au commerce international ont été les plus lourdement sanctionnés : les actions des grandes multinationales industrielles et technologiques ont chuté (par exemple, Tesla a cédé –5,5 % et Microsoft –2,4 % sur la séance).

Le mouvement s''est rapidement propagé à l''**Europe** et à l''**Asie**. Le 3 avril et les jours suivants, les principales places boursières mondiales ont enchaîné les séances de baisse. À Paris, le CAC 40 a ouvert en chute libre (-6,8 % le 7 avril). À Francfort, le DAX a décroché de 10 % peu après l''ouverture, du jamais vu depuis les paniques de 2020. En **Asie**, les marchés ont également vacillé : Tokyo, Shanghai, Hong Kong, Sydney ont tous enregistré des reculs de 4 à 12 % sur fond de panique liée à l''escalade commerciale. Ces baisses généralisées traduisent un **retour de l''aversion au risque**. Les investisseurs redoutent qu''une guerre commerciale prolongée ne plombe la croissance mondiale, n''érode les bénéfices des entreprises multinationales et n''entraîne, in fine, une récession globale. 

Logiquement, on a observé un **reflux vers les valeurs refuge**. Le marché obligataire américain a profité d''achats de précaution, ce qui a fait baisser les rendements des emprunts d''État à 10 ans (les investisseurs privilégiant la sécurité des T-Bonds face aux actions volatiles). Le **dollar** lui-même a joué son rôle de valeur refuge : malgré l''origine américaine du choc, le billet vert s''est maintenu à un niveau élevé contre l''euro et les devises émergentes, certains acteurs anticipant que les autres économies souffriront tout autant sinon plus de ce conflit commercial. Mais c''est surtout l''**or** qui a bénéficié de son statut de refuge universel : le métal jaune a atteint de nouveaux sommets historiques autour de 3 167 $ l''once dans les jours suivant les annonces, signe que beaucoup cherchent à se protéger de la tempête. En revanche, le **pétrole** a décroché, comme mentionné, car la menace d''un coup de frein sur le commerce et l''industrie laisse présager une demande énergétique plus faible : le baril de WTI est tombé sous les 60 $ pour la première fois depuis 2021. De même, des matières premières industrielles comme le cuivre ou le minerai de fer ont vu leurs cours fléchir, sensibles à l''anticipation d''une moindre activité mondiale.

Un cas à part mérite attention : celui des **cryptomonnaies**. Considérées d''ordinaire comme des actifs à risque, elles ont initialement suivi le mouvement de défiance générale avant de montrer une certaine **résilience**. Juste après l''annonce des tarifs, le marché des cryptos a vacillé : le **Bitcoin** a chuté d''environ **6 %**, passant de 88 000 $ à environ **82 000 $** en l''espace de quelques heures dans la nuit du 2 au 3 avril. Les autres cryptomonnaies (« altcoins ») ont corrigé encore plus brutalement, avec -8 % pour l''Ether et des chutes dépassant 10 % pour des tokens comme le XRP, le Dogecoin ou Solana. En une nuit, c''est plus de **100 milliards de dollars** de valorisation qui se sont évaporés du marché crypto, les investisseurs fuyant les actifs risqués dans un premier temps. Toutefois, cette baisse a été de courte durée. Très vite, le Bitcoin a stabilisé son cours et montré des signes de rebond. Sur les 24 heures qui ont suivi, la **capitalisation totale du marché crypto est restée quasiment stable**, une performance notable alors que toutes les autres classes d''actifs chutaient. Le Bitcoin a oscillé dans une fourchette étroite autour de 83 000 $ (±1 %), finissant même légèrement en hausse, ce qui en fait l''un des rares actifs mondiaux en territoire positif sur la journée suivant le choc. Cette surprenante résilience a conduit certains observateurs à qualifier le Bitcoin de nouvel "or numérique" capable de jouer un rôle de valeur refuge alternative lorsque la confiance dans le système économique vacille.

Les valeurs liées à la crypto (actions d''entreprises crypto cotées) ont tout de même subi le contrecoup initial. Par exemple, le titre de la plateforme américaine **Coinbase** a plongé de **-7,7 %** le 3 avril, et des sociétés exposées au Bitcoin comme **MicroStrategy** ont cédé plus de 5 %. Mais ces reculs restent contenus au regard des baisses bien plus fortes de certains secteurs traditionnels (automobile, finance, etc.). Des analystes soulignent que la correction sur les crypto-actifs a été **moins sévère** que dans d''autres industries. La corrélation du Bitcoin avec les marchés boursiers semble avoir diminué à mesure que son adoption mondiale a augmenté. *"La nature sans frontière du crypto permet aux investisseurs du monde entier de se couvrir contre les incertitudes macroéconomiques"*, note un spécialiste, soulignant que la crise actuelle pourrait même renforcer à terme l''attrait de solutions décentralisées si les politiques protectionnistes érodent la confiance dans les monnaies fiduciaires. Ainsi, paradoxalement, les actions de Trump pourraient **stimuler l''intérêt pour le Bitcoin sur le long terme**, certains y voyant un actif échappant aux manipulations étatiques et à l''affaiblissement potentiel de l''hégémonie du dollar. Pour l''heure, toutefois, la volatilité reste élevée et les investisseurs crypto demeurent prudents, conscients que si la situation économique se détériore trop, même les actifs numériques pourraient finir par en souffrir. 

## Les secteurs économiques les plus touchés 
Derrière les agrégats macroéconomiques, la tempête des droits de douane frappe de manière **inégale selon les secteurs**. Certaines industries, de par leur exposition commerciale ou leur chaîne de production internationale, sont en première ligne, tandis que d''autres sont relativement épargnées ou bénéficient d''exemptions.

- **Automobile** : C''est l''un des secteurs emblématiques visés par Donald Trump, qui dénonce depuis longtemps le déséquilibre dans les échanges de véhicules. L''administration américaine a annoncé un tarif punitif de **25 %** sur **toutes les automobiles étrangères** vendues sur le sol américain. Ce niveau était déjà appliqué aux camions légers depuis des décennies (taxe dite "chicken tax"), mais il s''étendrait maintenant aux voitures particulières. L''impact sera différencié : les constructeurs **européens** (Allemands surtout) et **japonais** risquent de voir fondre leurs ventes de voitures aux USA ou leurs marges (à moins de réduire drastiquement leurs prix). Des marques comme BMW, Mercedes, Toyota ou Honda, qui exportent vers les États-Unis, devront soit absorber une partie de la taxe, soit répercuter la hausse sur le prix de vente, au risque de perdre des clients. À l''inverse, certains groupes ayant déjà une forte implantation de production sur le sol américain seront moins affectés. Par exemple, **Stellantis** (maison-mère de Chrysler, Jeep, Peugeot, Fiat…) possède plusieurs usines aux États-Unis via ses marques américaines, ce qui lui permet d''échapper en partie aux surtaxes sur les véhicules finis. En Europe, les constructeurs moins présents aux USA, comme **Renault** ou certains fabricants de niche, subiront peu de dommages directs, mais pourraient souffrir indirectement si la guerre commerciale freine la croissance mondiale ou renchérit certains composants importés. Notons que l''automobile est un secteur à la **chaîne de valeur très intégrée** : les allers-retours de pièces détachées entre pays (moteurs, électronique, etc.) risquent d''être taxés à chaque étape, renchérissant le coût de fabrication final d''une voiture. L''économiste Isabelle Méjean rappelle que *"certaines pièces d''Airbus sont produites aux États-Unis, tandis que des composants de Boeing viennent de France. À chaque aller-retour, une taxe s''appliquera"* – un exemple pour l''aéronautique qui vaut aussi pour l''automobile. Ainsi, même une voiture "made in USA" utilise de l''acier canadien, des semi-conducteurs taïwanais ou des capteurs européens qui, eux, peuvent être frappés de droits de douane, augmentant son coût de production. 

- **Aéronautique & spatial** : Ce secteur est particulièrement vulnérable car il repose sur un écosystème transatlantique dense. Par exemple, Airbus et Boeing, les deux géants du secteur, ont des fournisseurs et sous-traitants de part et d''autre de l''Atlantique. On estime que **11 % des ventes de l''industrie aérospatiale française** sont destinées aux États-Unis. Des droits de douane de 20 % sur ces exportations alourdiraient considérablement le coût pour les compagnies aériennes clientes ou pour Boeing qui achète certaines pièces en Europe. De plus, Airbus pourrait voir ses avions finis subir une taxe à l''importation s''ils sont vendus à des compagnies américaines, ce qui rendrait ses appareils moins compétitifs face à Boeing sur le marché US. Inversement, Boeing pourrait pâtir de représailles de l''UE (dans le cadre du vieux litige Airbus-Boeing), mais surtout, les composants qu''il importe (certains en provenance d''Europe) sont dorénavant plus chers. L''aéronautique est un secteur où les marges sont serrées et les contrats à long terme : une augmentation des coûts de 20 % en milieu de programme pourrait mettre en danger la rentabilité de projets et pousser les entreprises à renégocier avec leurs clients. **Toute la chaîne** pourrait ressentir un effet boule de neige, des grands motoristes (Safran, General Electric) aux innombrables PME fournissant des pièces de haute précision. En 2018, les taxes sur l''acier et l''aluminium décidées par Trump avaient déjà renchéri les matières premières et pesé sur les coûts de l''aéro; en 2025, le choc est démultiplié et **aucune exemption de long terme n''est garantie** malgré les négociations en cours.

- **Technologies et électronique** : Les équipements électroniques, les smartphones, ordinateurs et autres appareils high-tech sont au cœur des échanges entre la Chine, les États-Unis et l''Europe. Durant son premier mandat, Trump avait épargné certains produits de grande consommation (comme les smartphones) de la guerre tarifaire, conscient de leur importance pour les consommateurs. Mais cette fois, le coup de balai tarifaire est large. De nombreux produits **high-tech assemblés en Chine** (smartphones, télévisions, consoles de jeu) écopent de tarifs de 34 %, ce qui pourrait augmenter significativement leurs prix aux États-Unis. Des marques comme **Apple** sont particulièrement concernées : l''iPhone et autres appareils Apple sont majoritairement fabriqués en Chine ou en Asie et importés aux USA. Apple pourrait être contrainte soit d''absorber une partie du surcoût (réduisant ses marges), soit de relever ses prix de vente, au risque de freiner la demande. De plus, la Chine brandit en retour la menace de **restrictions sur les exportations de terres rares** et métaux critiques, indispensables à l''électronique et aux technologies vertes (magnets, batteries, puces…). Une telle restriction frapperait de plein fouet des secteurs comme les **semi-conducteurs**, le **véhicule électrique** ou les **smartphones**, en aggravant la pénurie de certains composants. Fait notable toutefois, les **semi-conducteurs eux-mêmes ne sont pas visés directement par les nouveaux tarifs américains** – sans doute parce que les États-Unis ne veulent pas perturber davantage un secteur déjà en tension depuis la pandémie, et sur lequel leur propre industrie (Intel, Qualcomm…) dépend d''un écosystème international. Il n''empêche que l''électronique mondiale fonctionne en flux tendu et chaîne mondiale : tout renchérissement ou embargo se répercute sur les délais et les coûts de production, mettant à mal notamment les fabricants d''appareils grand public, les opérateurs télécoms (pour leurs équipements réseaux) ou encore les jeunes pousses innovantes qui ne pourront absorber ces surcoûts.

- **Agriculture & agroalimentaire** : Ce secteur se trouve souvent en première ligne des guerres commerciales, car il touche à des produits emblématiques et sensibles politiquement. Dans le cas présent, l''agriculture américaine pourrait être victime collatérale des représailles étrangères. La **Chine** a d''ores et déjà suspendu certains achats de produits agricoles américains (comme ce fut le cas en 2018) pour faire pression sur Washington. Le soja américain, dont la Chine était le premier client, pourrait se retrouver en surabondance, faisant chuter les prix et les revenus des fermiers du Midwest. De même, l''Europe pourrait décider de cibler des produits agricoles US (blé, maïs, oranges de Floride, whisky bourbon, etc.) dans sa liste de rétorsions pour infliger une douleur politique dans les États ruraux pro-Trump. À l''inverse, l''agriculture européenne et mondiale ressentira les effets du ralentissement économique : moins de pouvoir d''achat global signifie potentiellement moins de débouchés pour des produits comme le vin, le fromage, la viande haut de gamme, etc. Comme mentionné, les **vins et spiritueux français** anticipent une forte baisse de leurs exportations aux États-Unis (premier marché pour ces produits). Le **cognac**, dont 40 % des ventes partent chaque année aux États-Unis, est particulièrement sous pression. Si les tarifs restent en place longtemps, ces producteurs devront peut-être chercher de nouveaux marchés ou réduire leur production. Par ailleurs, certains pays émergents fournisseurs de produits agricoles (Amérique du Sud, Asie du Sud-Est) pourraient eux aussi perdre des opportunités d''exportation vers les US et la Chine à cause de la contraction des échanges.

- **Industries de base (acier, aluminium, bois, chimie)** : Ces secteurs avaient déjà fait l''objet de mesures protectionnistes lors du premier mandat de Trump (tarifs de 25 % sur l''acier et 10 % sur l''aluminium dès 2018). En 2025, ces industries restent protégées voire renforcées : les nouveaux tarifs généraux n''affectent pas davantage l''acier et l''aluminium (puisqu''ils sont déjà surtaxés depuis 2018), et Trump cherche toujours à favoriser les sidérurgistes et métallurgistes américains. Le **bois de construction** et certains matériaux de base sont également exemptés des hausses, possiblement pour ne pas renchérir le coût de secteurs comme le bâtiment aux États-Unis. Ainsi, les industries US d''acier, d''aluminium ou du bois pourraient bénéficier d''un surcroît de demande locale faute d''importations compétitives – c''est du moins l''objectif affiché. Cependant, la médaille a un revers : si ces secteurs en amont vont mieux, les industries consommatrices en aval (construction, automobile, emballage, etc.) payent plus cher leurs intrants, ce qui peut entraîner des pertes d''emplois bien plus nombreuses que celles sauvées en amont. Du côté européen et mondial, les producteurs d''acier (ex : sidérurgistes allemands, coréens, turcs) souffrent de ne plus accéder librement au marché américain, ce qui peut provoquer des surcapacités et pousser à la baisse des prix à l''échelle mondiale, fragilisant les acteurs.

- **Pharmacie et produits médicaux** : Bonne nouvelle pour ce secteur, il a été **épargné** par les surtaxes. Les médicaments et produits pharmaceutiques ne sont pas concernés par l''augmentation des droits de douane américains, sans doute pour des raisons à la fois humanitaires (ne pas renchérir le coût des médicaments pour les malades américains) et stratégiques (beaucoup de principes actifs viennent d''Inde ou d''Europe et les taxer pourrait créer des pénuries de médicaments). Ainsi, des grands groupes comme Pfizer, Johnson & Johnson, Novartis ou Sanofi ne voient pas leurs échanges perturbés directement. La demande pharmaceutique est de toute façon assez *« peu élastique »*, comme le notent les experts : même en cas de taxe, un hôpital achètera un médicament vital, quitte à en répercuter le coût sur l''assureur ou l''usager. Néanmoins, étant donné le climat de tension générale, le secteur n''est pas totalement à l''abri de mesures indirectes (retards dans les autorisations d''exportation, etc.), et il subit aussi l''effet change (un dollar fort ou faible modifie le prix des médicaments importés).

En résumé, les **secteurs les plus touchés** par ces hostilités commerciales sont ceux liés aux échanges internationaux et aux chaînes d''approvisionnement complexes : automobile, aéronautique, électronique, machines industrielles, agriculture d''exportation. Certains secteurs **protégés ou stratégiques** (défense, pharma, énergie) sont volontairement exclus du champ de bataille pour éviter de se tirer une balle dans le pied. Mais l''ensemble du tissu productif mondial ressentira tôt ou tard les effets de la hausse généralisée des coûts et de la baisse de confiance générées par cette guerre commerciale.

## Risques d''escalade et perspectives des tensions commerciales 
La situation actuelle présente tous les ingrédients d''une **escalade commerciale** durable. Chaque camp campe sur ses positions et brandit de nouvelles mesures, ce qui laisse craindre un **cercle vicieux de représailles**. Du côté américain, Donald Trump se montre inflexible malgré le tumulte boursier et les protestations internationales. Il a même minimisé la panique financière en la comparant à *"un traitement nécessaire dont il faut accepter les effets secondaires pour guérir le patient"*, signifiant par là qu''il considère la chute des marchés comme un mal passager au service d''un bien économique supérieur. La Maison-Blanche semble prête à endurer quelques turbulences si c''est le prix à payer pour forcer ses partenaires à la négociation. Trump a averti sur son réseau social qu''il ne voulait pas voir les Américains *"faiblir"* face aux contre-mesures étrangères, et a réitéré que selon lui la **Chine** est *"le plus grand profiteur de tous"* dans le système actuel. Cette rhétorique combative réduit la marge de manœuvre pour un compromis rapide.

En face, les **réactions des autres puissances** indiquent une détermination à ne pas céder au chantage. La **Chine** a frappé fort, comme on l''a vu, avec des tarifs symétriques et des restrictions ciblées qui marquent une rupture par rapport à sa retenue de 2018. L''Union européenne, quant à elle, coordonne une réponse collective et cherche à impliquer d''autres partenaires pour isoler les États-Unis. Une **coordination internationale** pourrait voir le jour entre certains acteurs majeurs lésés : par exemple, on évoque des consultations entre **Japon, Corée du Sud et Chine** pour adopter une attitude commune et ne pas se laisser diviser par Washington. Si de grands blocs de pays unissent leurs forces (par exemple UE + Asie de l''Est), les États-Unis pourraient se retrouver confrontés à un front économique uni représentant une part très importante du marché mondial, ce qui affaiblirait leur position de négociation. C''est précisément le risque de la stratégie tarifaire tous azimuts : en **s''attaquant simultanément** à presque tous ses partenaires, l''administration Trump les pousse à faire cause commune. On voit déjà un rapprochement sino-européen sur la défense du multilatéralisme, et l''UE a mentionné vouloir activer des mécanismes de l''OMC (même si celle-ci est paralysée) et son nouvel instrument anti-coercition.

Le **scénario du pire** serait une fuite en avant incontrôlée. Si chaque camp ajoute des couches de tarifs ou d''autres barrières (quotas d''importation, normes discriminantes, etc.), on pourrait se diriger vers une situation proche des années 1930 où le commerce mondial s''était effondré sous l''effet des guerres tarifaires. Les économistes soulignent qu''une telle spirale protectionniste ferait principalement des perdants de part et d''autre, le commerce étant un *jeu à somme positive qui se transforme en jeu perdant-perdant* en cas de guerre économique généralisée. L''OMC n''ayant plus vraiment de moyen d''arbitrer (les États-Unis bloquant son organe d''appel depuis 2019), il n''existe pas de garde-fou institutionnel efficace pour freiner l''escalade. Le risque est donc que les tensions s''étendent à de **nouveaux domaines** : on parle déjà de l''éventualité d''une guerre des **devises** (si la Chine décidait de déprécier fortement le yuan pour compenser les tarifs, ou si les États-Unis accusaient d''autres pays de manipuler leur monnaie), ou d''une guerre **technologique** plus marquée (restrictions sur les exportations de technologies sensibles, interdiction d''entreprises comme on l''a vu avec Huawei par le passé, etc.). L''Europe menaçant de s''en prendre aux Big Tech américaines est un signal que le conflit commercial pourrait déborder sur le terrain du **numérique** et des services, ouvrant un front totalement nouveau.

Tous les pays ne souhaitent cependant pas aller au clash. Comme évoqué, certains – en particulier des pays de taille moyenne ou petite – choisissent la retenue pour ne pas aggraver la situation. La **Suisse**, malgré un traitement dur (31 % de tarifs américains), ne riposte pas. Plusieurs nations d''Asie du Sud-Est préfèrent **négocier** discrètement des exemptions ou des accords bilatéraux avec Washington plutôt que de riposter frontalement. Ces stratégies diversifiées pourraient limiter l''ampleur de l''escalade dans certains cas. Par exemple, si Trump concède des arrangements à certains alliés stratégiques (Japon, Australie, etc.) en échange d''autres concessions, la tension pourrait s''atténuer régionalement. De même, l''UE cherchera peut-être un terrain d''entente via la diplomatie (comme ce fut le cas en 2018 où une trêve avait été négociée sur les automobiles avec la Commission européenne). 

Néanmoins, à ce stade, la **probabilité d''une intensification** reste élevée selon la plupart des observateurs. La pression populaire et politique s''accroît sur les dirigeants pour qu''ils ne "cèdent" pas face à Trump, ce qui réduit la possibilité de compromis perçu comme une faiblesse. **À court terme, peu d''issues favorables semblent en vue**. Il faudra sans doute que les coûts économiques deviennent trop douloureux pour l''un ou l''autre camp pour les pousser à revenir à la table des négociations. D''ici là, les prochains mois pourraient voir une succession de **coups pour coups** : l''UE appliquer ses surtaxes en avril-mai, Trump répliquer peut-être en élargissant encore les produits taxés (voire en relevant les taux au-delà de 34 % pour la Chine, comme il l''a menacé verbalement), la Chine intensifier ses propres restrictions (par exemple en ciblant plus de firmes US en Chine, ou en limitant ses exportations d''autres biens stratégiques). Le spectre d''une **"déglobalisation"** forcée plane désormais sur l''économie mondiale, avec le risque d''une fragmentation durable en blocs commerciaux hostiles si aucune détente ne se profile.

## Conclusion : quel avenir à moyen et long terme ? 
Si les mesures tarifaires de Donald Trump devaient **perdurer ou s''aggraver**, les répercussions à moyen et long terme pourraient remodeler en profondeur l''ordre économique mondial. Un scénario de conflit prolongé verrait sans doute un **affaiblissement durable de la croissance mondiale**. Plusieurs institutions et experts tirent la sonnette d''alarme : selon les premières simulations, la multiplication des barrières douanières pourrait retrancher plus d''un point de PIB mondial d''ici 2026 par rapport aux tendances actuelles, en raison de la chute des échanges et de l''effondrement de la confiance des entreprises en l''avenir. L''augmentation des coûts importés nourrirait une inflation plus forte un peu partout, érodant le pouvoir d''achat des ménages (surtout des plus modestes, pour qui les produits bon marché importés sont importants). On redoute une forme de **stagflation mondiale** – faible croissance couplée à des prix en hausse – rappelant les heures sombres des années 1970. Les banques centrales seraient alors confrontées à des arbitrages douloureux, comme la Fed américaine qui devrait choisir entre soutenir l''activité ou juguler l''inflation importée.

Sur le long terme, la **carte de la mondialisation** pourrait être redessinée. Exclues du marché américain ou lourdement taxées, de nombreuses nations chercheraient à **diversifier leurs partenariats commerciaux**. On assisterait à l''accélération d''accords commerciaux régionaux ou bilatéraux entre autres grandes zones économiques, contournant les États-Unis. Par exemple, la conclusion d''accords de libre-échange déjà en négociation pourrait être précipitée : l''**Europe** pourrait finaliser l''accord avec le **Mercosur** ou avancer sur un accord avec l''**Inde** pour ouvrir de nouveaux débouchés hors USA. L''**Asie** intensifierait ses intégrations régionales (via l''ASEAN, le RCEP, etc.). L''**Afrique** et l''**Amérique du Sud** pourraient resserrer leurs liens avec l''Europe ou la Chine dans une sorte de réalignement des blocs commerciaux. En somme, le reste du monde, qui représente 96 % de la population, chercherait activement à **contourner les États-Unis** pour continuer à échanger librement. Ironiquement, les États-Unis – environ 4 % de l''humanité – risqueraient de se **marginaliser** progressivement s''ils persistent dans une posture isolationniste, car les autres acteurs trouveront des alternatives pour commercer entre eux. Déjà, on voit émerger des alliances et des stratégies de substitution : la Chine se tourne vers l''Asie et l''Europe, l''Europe vers d''autres partenaires, etc. 

À l''intérieur même des États-Unis, des **pressions internes** finiront par se faire sentir. Les industries exportatrices américaines (aviation, agriculture, automobile) pourraient accentuer leur lobbying contre les tarifs si elles perdent définitivement des marchés à cause des représailles étrangères. De même, les consommateurs américains, une fois confrontés durablement à la hausse des prix dans les magasins, pourraient se retourner contre ces politiques si elles ne produisent pas rapidement les bénéfices promis. Pour Trump, le pari est qu''à long terme les emplois reviennent et la base électorale applaudisse. Mais si au contraire des licenciements surviennent dans des secteurs pénalisés par les représailles (par exemple, des agriculteurs ruinés par la perte du marché chinois), le soutien politique pourrait vaciller.

Il est toutefois possible qu''avant d''en arriver à un scénario extrême de "guerre commerciale froide" durable, les parties prenantes optent pour une **désescalade négociée**. L''histoire des relations commerciales montre qu''après l''épreuve de force, viennent souvent les compromis. Trump lui-même a souvent utilisé les tarifs comme levier pour obtenir des accords plus favorables (ce fut le cas avec le Canada/Mexique pour renégocier l''ALENA en USMCA, ou avec la Chine pour l''accord commercial partiel de janvier 2020). On peut imaginer qu''à un certain point, l''administration américaine propose à l''Europe et au Japon une suppression réciproque de tous les tarifs industriels – offre que l''UE avait déjà mise sur la table – ou qu''elle négocie avec Pékin un **nouvel accord commercial global** rééquilibré (par exemple, engagements d''achat massif de produits américains par la Chine, ouvertures accrues de son marché, protection de la propriété intellectuelle, etc., en échange d''une levée des tarifs). La difficulté sera de concilier l''approche multilatérale souhaitée par l''UE et la Chine avec la préférence de Trump pour les deals bilatéraux de force à force. 

En attendant, l''**incertitude** sera le maître-mot des prochains trimestres. Les chefs d''entreprise, pris en étau, risquent de geler ou différer des décisions d''investissement face à un environnement aussi volatil. Les chaînes logistiques internationales, déjà éprouvées par la pandémie de Covid, devront peut-être se **reconfigurer** en urgence pour éviter les zones de tarif élevé : on pourrait voir encore plus d''usines délocalisées du couple États-Unis/Chine vers des pays tiers non frappés (à condition qu''il en reste…), ou l''établissement de *hubs* de transit dans des pays neutres pour ré-étiqueter l''origine des produits et contourner les tarifs (pratiques de **transbordement** douanier). Certaines entreprises adopteront une stratégie de **"near-shoring"** ou de localisation plus poussée de leur production pour réduire leur exposition aux frontières tarifaires. Ce mouvement de fond vers une moindre interdépendance – déjà entamé pour des raisons sanitaires et géopolitiques – s''en trouverait accéléré.

En définitive, les **guerres commerciales** de cette ampleur sont rarement propices à des issues positives. Comme l''écrit un commentateur, *« inutile de chercher : il n''y a aucune logique économique chez Trump »* dans cette surenchère protectionniste, si ce n''est une logique politique. La théorie économique et l''expérience historique suggèrent que tout le monde y perd : consommateurs, producteurs, investisseurs, et que les avantages espérés (relocalisations, souveraineté retrouvée) peuvent être largement contrebalancés par les dommages collatéraux. À moyen terme, si les tarifs de Trump restent en place ou empirent, le **risque d''un affaiblissement général de l''économie mondiale** est réel, avec un système commercial international fragmenté et moins efficace. La seule lueur d''espoir serait qu''une **prise de conscience** intervienne devant l''ampleur des dégâts, conduisant les dirigeants à revenir à la table des négociations. Un accord global de réduction réciproque des barrières (même s''il sauve les apparences pour chaque camp) serait alors la porte de sortie pour éviter une décennie perdue. En attendant, l''économie mondiale navigue en eaux troubles, suspendue aux tweets et décisions de Washington comme jamais, dans ce qui s''annonce comme l''un des bras de fer commerciaux les plus décisifs de ce début de XXI<sup>e</sup> siècle.',
      'https://images.unsplash.com/photo-1541199249251-f713e6145474?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      CURRENT_TIMESTAMP,
      CURRENT_TIMESTAMP
    );
  END IF;
END $$;